### ISSUE TITLE
[Feature request] An option to stop the running service

### ISSUE THREAD

**Issue by Pastafarianist** [ilijamt/android-adbm#3]
As soon as the app launches, the service is started in the background. There is no option in the interface to stop it. Yet it consumes resources and it is hardly a good idea to keep such service running on a device that is used for purposes other than development. Would you consider adding such option in the interface?

**Comment by ilijamt** [comment]
I'll see about it as soon as I have time, it is not difficult to do, hopefully in a week or so

**Comment by ilijamt** [comment]
It took a while, didn't have time, expect it in a couple of days for a new update
